name: 'Tar required WebRTC header files.'
description: 'Tar required WebRTC header files to be used by your application.'
inputs:
  srcdir:
    description: 'The source dir where the WebRTC library has been checked out.'
    required: true
  tarball:
    description: 'Path of the output tarball (absolute or relative to the source directory).'
    required: true
  exclude:
    description: 'The paths to exclude from header copying'
    required: true
    default: out build buildtools third_party/blink third_party/llvm-build third_party/win_build_output third_party/android_ndk third_party/catapult
runs:
  using: "composite"
  steps:
    - shell: bash
      working-directory: "${{ inputs.srcdir }}"
      run: |
        set -x
        if [ -z "${{ inputs.tarball }}" ]; then
          echo "Invalid output tarball: ${{ inputs.tarball }}"
          exit 1
        fi

        mkdir -p $(dirname "${{ inputs.tarball }}")

        for p in ${{ inputs.exclude }}
        do
          EXCLUDE="$EXCLUDE -path ./${p} -prune -o"
        done

        find . $EXCLUDE -type f -a \( -name "*.h" -o -name LICENSE -o -name COPYING \) -print -exec tar -rvf '${{ inputs.tarball }}' "{}" \;
