name: 'Copy required WebRTC header files.'
description: 'Copy required WebRTC header files to be used by your application.'
inputs:
  srcdir:
    description: 'The source dir where the WebRTC library has been checked out.'
    required: true
  outdir:
    description: 'The path where to copy the relevant headers.'
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      id: copy-headers
      run: |
        if [ -z "${{ inputs.outdir }}" ];
          echo "Invalid output dir ${{ inputs.outdir }}"
          exit 1
        fi
        if [ -z "${{ inputs.srcdir }}" ] || [ ! -d "${{ inputs.srcdir }}" ];
          echo "Invalid source dir ${{ inputs.srcdir }}"
          exit 1
        fi
        mkdir -p "${{ inputs.outdir }}"

        # OSX and their non-GNU commands :)
        CP=cp
        if [[ "$OSTYPE" == "darwin"* ]]; then
          CP=gcp
        fi
        cd "${{ inputs.srcdir }}"
        find -type f -not -path './out/*' -not -path './build/*' -not -path './buildtools/*' -a \( -name '*.h' -o -name README -o -name LICENSE -o -name COPYING \) | \
          xargs -I '{}' $CP --parents '{}' ${{ inputs.outdir }}
