name: 'Copy required WebRTC header files.'
description: 'Copy required WebRTC header files to be used by your application.'
inputs:
  srcdir:
    description: 'The source dir where the WebRTC library has been checked out.'
    required: true
  outdir:
    description: 'The path where to copy the relevant headers.'
    required: true
  exclude:
    description: 'The paths to exclude from header copying'
    required: true
    default: out build buildtools third_party/blink third_party/llvm-build
runs:
  using: "composite"
  steps:
    - shell: bash
      id: copy-headers
      run: |
        set -x
        if [ -z "${{ inputs.outdir }}" ]; then
          echo "Invalid output dir ${{ inputs.outdir }}"
          exit 1
        fi
        if [ -z "${{ inputs.srcdir }}" ] || [ ! -d "${{ inputs.srcdir }}" ]; then
          echo "Invalid source dir ${{ inputs.srcdir }}"
          exit 1
        fi
        mkdir -p "${{ inputs.outdir }}"

        # OSX and their non-GNU commands :)
        CP=cp
        if [[ "$OSTYPE" == "darwin"* ]]; then
          CP=gcp
        fi
        for p in ${{ inputs.exclude }}
        do
          EXCLUDE="$EXCLUDE -not -path \"./${p}/*\""
        done
        cd "${{ inputs.srcdir }}"
        find . -type f $EXCLUDE -a \( -name "*.h" -o -name LICENSE -o -name COPYING \) | xargs -I '{}' $CP --parents '{}' "${{ inputs.outdir }}"
